//#line 2 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the roboteq_sdc2130 package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __roboteq_sdc2130__ROBOTEQ_SDC2130_DYNPARAMSCONFIG_H__
#define __roboteq_sdc2130__ROBOTEQ_SDC2130_DYNPARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace roboteq_sdc2130
{
  class roboteq_sdc2130_dynparamsConfigStatics;
  
  class roboteq_sdc2130_dynparamsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(roboteq_sdc2130_dynparamsConfig &config, const roboteq_sdc2130_dynparamsConfig &max, const roboteq_sdc2130_dynparamsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const roboteq_sdc2130_dynparamsConfig &config1, const roboteq_sdc2130_dynparamsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, roboteq_sdc2130_dynparamsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const roboteq_sdc2130_dynparamsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, roboteq_sdc2130_dynparamsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const roboteq_sdc2130_dynparamsConfig &config) const = 0;
      virtual void getValue(const roboteq_sdc2130_dynparamsConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T roboteq_sdc2130_dynparamsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (roboteq_sdc2130_dynparamsConfig::* field);

      virtual void clamp(roboteq_sdc2130_dynparamsConfig &config, const roboteq_sdc2130_dynparamsConfig &max, const roboteq_sdc2130_dynparamsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const roboteq_sdc2130_dynparamsConfig &config1, const roboteq_sdc2130_dynparamsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, roboteq_sdc2130_dynparamsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const roboteq_sdc2130_dynparamsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, roboteq_sdc2130_dynparamsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const roboteq_sdc2130_dynparamsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const roboteq_sdc2130_dynparamsConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, roboteq_sdc2130_dynparamsConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, roboteq_sdc2130_dynparamsConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<roboteq_sdc2130_dynparamsConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(roboteq_sdc2130_dynparamsConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("FeedForward_left"==(*i)->name){FeedForward_left = boost::any_cast<double>(val);}
        if("P_left"==(*i)->name){P_left = boost::any_cast<double>(val);}
        if("I_left"==(*i)->name){I_left = boost::any_cast<double>(val);}
        if("D_left"==(*i)->name){D_left = boost::any_cast<double>(val);}
        if("I_lim_left"==(*i)->name){I_lim_left = boost::any_cast<double>(val);}
        if("Ramp_left"==(*i)->name){Ramp_left = boost::any_cast<double>(val);}
        if("max_left"==(*i)->name){max_left = boost::any_cast<double>(val);}
        if("deadband_left_fw"==(*i)->name){deadband_left_fw = boost::any_cast<double>(val);}
        if("deadband_left_bw"==(*i)->name){deadband_left_bw = boost::any_cast<double>(val);}
        if("FeedForward_right"==(*i)->name){FeedForward_right = boost::any_cast<double>(val);}
        if("P_right"==(*i)->name){P_right = boost::any_cast<double>(val);}
        if("I_right"==(*i)->name){I_right = boost::any_cast<double>(val);}
        if("D_right"==(*i)->name){D_right = boost::any_cast<double>(val);}
        if("I_lim_right"==(*i)->name){I_lim_right = boost::any_cast<double>(val);}
        if("Ramp_right"==(*i)->name){Ramp_right = boost::any_cast<double>(val);}
        if("max_right"==(*i)->name){max_right = boost::any_cast<double>(val);}
        if("deadband_right_fw"==(*i)->name){deadband_right_fw = boost::any_cast<double>(val);}
        if("deadband_right_bw"==(*i)->name){deadband_right_bw = boost::any_cast<double>(val);}
        if("filter_order"==(*i)->name){filter_order = boost::any_cast<int>(val);}
        if("filter_cutoff"==(*i)->name){filter_cutoff = boost::any_cast<double>(val);}
      }
    }

    double FeedForward_left;
double P_left;
double I_left;
double D_left;
double I_lim_left;
double Ramp_left;
double max_left;
double deadband_left_fw;
double deadband_left_bw;
double FeedForward_right;
double P_right;
double I_right;
double D_right;
double I_lim_right;
double Ramp_right;
double max_right;
double deadband_right_fw;
double deadband_right_bw;
int filter_order;
double filter_cutoff;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double FeedForward_left;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double P_left;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double I_left;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double D_left;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double I_lim_left;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Ramp_left;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_left;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double deadband_left_fw;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double deadband_left_bw;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double FeedForward_right;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double P_right;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double I_right;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double D_right;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double I_lim_right;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double Ramp_right;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double max_right;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double deadband_right_fw;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double deadband_right_bw;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int filter_order;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double filter_cutoff;
//#line 255 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("roboteq_sdc2130_dynparamsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const roboteq_sdc2130_dynparamsConfig &__max__ = __getMax__();
      const roboteq_sdc2130_dynparamsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const roboteq_sdc2130_dynparamsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const roboteq_sdc2130_dynparamsConfig &__getDefault__();
    static const roboteq_sdc2130_dynparamsConfig &__getMax__();
    static const roboteq_sdc2130_dynparamsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const roboteq_sdc2130_dynparamsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void roboteq_sdc2130_dynparamsConfig::ParamDescription<std::string>::clamp(roboteq_sdc2130_dynparamsConfig &config, const roboteq_sdc2130_dynparamsConfig &max, const roboteq_sdc2130_dynparamsConfig &min) const
  {
    return;
  }

  class roboteq_sdc2130_dynparamsConfigStatics
  {
    friend class roboteq_sdc2130_dynparamsConfig;
    
    roboteq_sdc2130_dynparamsConfigStatics()
    {
roboteq_sdc2130_dynparamsConfig::GroupDescription<roboteq_sdc2130_dynparamsConfig::DEFAULT, roboteq_sdc2130_dynparamsConfig> Default("Default", "", 0, 0, true, &roboteq_sdc2130_dynparamsConfig::groups);
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FeedForward_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FeedForward_left = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FeedForward_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("FeedForward_left", "double", 0, "Feedforward l", "", &roboteq_sdc2130_dynparamsConfig::FeedForward_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("FeedForward_left", "double", 0, "Feedforward l", "", &roboteq_sdc2130_dynparamsConfig::FeedForward_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.P_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.P_left = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.P_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("P_left", "double", 0, "P", "", &roboteq_sdc2130_dynparamsConfig::P_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("P_left", "double", 0, "P", "", &roboteq_sdc2130_dynparamsConfig::P_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.I_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.I_left = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.I_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_left", "double", 0, "I", "", &roboteq_sdc2130_dynparamsConfig::I_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_left", "double", 0, "I", "", &roboteq_sdc2130_dynparamsConfig::I_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.D_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.D_left = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.D_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("D_left", "double", 0, "D", "", &roboteq_sdc2130_dynparamsConfig::D_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("D_left", "double", 0, "D", "", &roboteq_sdc2130_dynparamsConfig::D_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.I_lim_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.I_lim_left = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.I_lim_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_lim_left", "double", 0, "Ilim", "", &roboteq_sdc2130_dynparamsConfig::I_lim_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_lim_left", "double", 0, "Ilim", "", &roboteq_sdc2130_dynparamsConfig::I_lim_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Ramp_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Ramp_left = 10000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Ramp_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("Ramp_left", "double", 0, "Ramp", "", &roboteq_sdc2130_dynparamsConfig::Ramp_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("Ramp_left", "double", 0, "Ramp", "", &roboteq_sdc2130_dynparamsConfig::Ramp_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_left = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_left = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("max_left", "double", 0, "max_left", "", &roboteq_sdc2130_dynparamsConfig::max_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("max_left", "double", 0, "max_left", "", &roboteq_sdc2130_dynparamsConfig::max_left)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.deadband_left_fw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.deadband_left_fw = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.deadband_left_fw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_left_fw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_left_fw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_left_fw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_left_fw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.deadband_left_bw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.deadband_left_bw = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.deadband_left_bw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_left_bw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_left_bw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_left_bw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_left_bw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.FeedForward_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.FeedForward_right = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.FeedForward_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("FeedForward_right", "double", 0, "Feedforward", "", &roboteq_sdc2130_dynparamsConfig::FeedForward_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("FeedForward_right", "double", 0, "Feedforward", "", &roboteq_sdc2130_dynparamsConfig::FeedForward_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.P_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.P_right = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.P_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("P_right", "double", 0, "P", "", &roboteq_sdc2130_dynparamsConfig::P_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("P_right", "double", 0, "P", "", &roboteq_sdc2130_dynparamsConfig::P_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.I_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.I_right = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.I_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_right", "double", 0, "I", "", &roboteq_sdc2130_dynparamsConfig::I_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_right", "double", 0, "I", "", &roboteq_sdc2130_dynparamsConfig::I_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.D_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.D_right = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.D_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("D_right", "double", 0, "D", "", &roboteq_sdc2130_dynparamsConfig::D_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("D_right", "double", 0, "D", "", &roboteq_sdc2130_dynparamsConfig::D_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.I_lim_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.I_lim_right = 10000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.I_lim_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_lim_right", "double", 0, "Ilim", "", &roboteq_sdc2130_dynparamsConfig::I_lim_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("I_lim_right", "double", 0, "Ilim", "", &roboteq_sdc2130_dynparamsConfig::I_lim_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Ramp_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Ramp_right = 10000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Ramp_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("Ramp_right", "double", 0, "Ramp2", "", &roboteq_sdc2130_dynparamsConfig::Ramp_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("Ramp_right", "double", 0, "Ramp2", "", &roboteq_sdc2130_dynparamsConfig::Ramp_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_right = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_right = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("max_right", "double", 0, "max_right", "", &roboteq_sdc2130_dynparamsConfig::max_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("max_right", "double", 0, "max_right", "", &roboteq_sdc2130_dynparamsConfig::max_right)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.deadband_right_fw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.deadband_right_fw = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.deadband_right_fw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_right_fw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_right_fw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_right_fw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_right_fw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.deadband_right_bw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.deadband_right_bw = 1000.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.deadband_right_bw = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_right_bw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_right_bw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("deadband_right_bw", "double", 0, "daed_left", "", &roboteq_sdc2130_dynparamsConfig::deadband_right_bw)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.filter_order = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.filter_order = 8;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.filter_order = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<int>("filter_order", "int", 0, "the order of the velocity filter", "", &roboteq_sdc2130_dynparamsConfig::filter_order)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<int>("filter_order", "int", 0, "the order of the velocity filter", "", &roboteq_sdc2130_dynparamsConfig::filter_order)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.filter_cutoff = 1.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.filter_cutoff = 10.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.filter_cutoff = 0.1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("filter_cutoff", "double", 0, "the cutoff frequency of the velocity filter", "", &roboteq_sdc2130_dynparamsConfig::filter_cutoff)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::ParamDescription<double>("filter_cutoff", "double", 0, "the cutoff frequency of the velocity filter", "", &roboteq_sdc2130_dynparamsConfig::filter_cutoff)));
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(roboteq_sdc2130_dynparamsConfig::AbstractGroupDescriptionConstPtr(new roboteq_sdc2130_dynparamsConfig::GroupDescription<roboteq_sdc2130_dynparamsConfig::DEFAULT, roboteq_sdc2130_dynparamsConfig>(Default)));
//#line 390 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h.template"
    
      for (std::vector<roboteq_sdc2130_dynparamsConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<roboteq_sdc2130_dynparamsConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    roboteq_sdc2130_dynparamsConfig __max__;
    roboteq_sdc2130_dynparamsConfig __min__;
    roboteq_sdc2130_dynparamsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const roboteq_sdc2130_dynparamsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static roboteq_sdc2130_dynparamsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &roboteq_sdc2130_dynparamsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const roboteq_sdc2130_dynparamsConfig &roboteq_sdc2130_dynparamsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const roboteq_sdc2130_dynparamsConfig &roboteq_sdc2130_dynparamsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const roboteq_sdc2130_dynparamsConfig &roboteq_sdc2130_dynparamsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<roboteq_sdc2130_dynparamsConfig::AbstractParamDescriptionConstPtr> &roboteq_sdc2130_dynparamsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<roboteq_sdc2130_dynparamsConfig::AbstractGroupDescriptionConstPtr> &roboteq_sdc2130_dynparamsConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const roboteq_sdc2130_dynparamsConfigStatics *roboteq_sdc2130_dynparamsConfig::__get_statics__()
  {
    const static roboteq_sdc2130_dynparamsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = roboteq_sdc2130_dynparamsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __ROBOTEQ_SDC2130_DYNPARAMSRECONFIGURATOR_H__
