#ifndef SHARED_H
#define SHARED_H
    enum states{STOP,START,READY,EXECUTE,SUSPENDED,GO_TO_UPPER_BRICK,GO_TO_LOWER_BRICK,BRICK_TO_MIDDLE,MIDDLE_TO_BOX,BOX_TO_MIDDLE,COMPLETED,GRASP_BRICK,RELEASE_BRICK,OPEN_GRIP};
#endif
