#ifndef SHARED_H
#define SHARED_H
    enum states{STOP,START,READY,EXECUTE,SUSPENDED,GO_TO_UPPER_BRICK,GO_TO_LOWER_BRICK,BRICK_TO_MIDDLE,MIDDLE_TO_BOX,BOX_TO_MIDDLE,COMPLETED,GRASP_BRICK,RELEASE_BRICK,OPEN_GRIP};

	#define PICKUP_BOX_XPOS -0.17
	#define PICKUP_BOX_XNEG -0.30
	#define PICKUP_BOX_YPOS 0.49
	#define PICKUP_BOX_YNEG 0.20
	#define PICKUP_BOX_ZPOS_UP 0.335 
	#define PICKUP_BOX_ZNEG_UP 0.32
	#define PICKUP_BOX_ZPOS_DOWN 0.315 
	#define PICKUP_BOX_ZNEG_DOWN 0.30
	#define PICKUP_BOX_CENTERX (PICKUP_BOX_XPOS+PICKUP_BOX_XNEG)/2.0
	#define PICKUP_BOX_CENTERY (PICKUP_BOX_YPOS+PICKUP_BOX_YNEG)/2.0
	#define PICKUP_BOX_CENTERZ (PICKUP_BOX_ZPOS_UP+PICKUP_BOX_ZNEG_UP)/2.0

	#define DELIVER_BOX_X 0.4811
	#define DELIVER_BOX_Y 0.1969
	
	#define BOXQ1 28.0
	#define BOXQ2 -50.0
	#define BOXQ3 -64.0
	#define BOXQ4 -6.23
	#define BOXQ5 -53.35
	#define BOXQ6 46.25
	
	#define MIDDLEQ1 132.43
	#define MIDDLEQ2 -33.9
	#define MIDDLEQ3 -92.15
	#define MIDDLEQ4 -6.23
	#define MIDDLEQ5 -53.35
	#define MIDDLEQ6 46.25
	
	#define PICKUP_BRICK_OFFSET 0.57
	

#endif
